/**
 *
 * @author Gaurab R. Gautam
 */
package boggle;

import static boggle.BoggleDemo.COL_SIZE;
import static boggle.BoggleDemo.ROW_SIZE;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


public class BoggleBoard extends javax.swing.JPanel {

    private final int cellWidth = 60;
    private char[][] boggle = null;
    
    /**
     * Creates new form BoggleBoard
     */
    public BoggleBoard() {
        initComponents();
    }
    
    public JTable getBoggleTable()
    {
        return this.boggleTable;
    }

    public char[][] getBoggle()
    {
        return this.boggle;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        radioButtonPanel = new javax.swing.JPanel();
        jRadioButton5x5 = new javax.swing.JRadioButton();
        jRadioButton4x4 = new javax.swing.JRadioButton();
        jRadioButton3x3 = new javax.swing.JRadioButton();
        boggleBoardScrollPane = new javax.swing.JScrollPane();
        boggleBoardPanel = new javax.swing.JPanel();

        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(328, 380));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        mainPanel.setMaximumSize(getPreferredSize());
        mainPanel.setPreferredSize(new java.awt.Dimension(328, 380));

        radioButtonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Board Size")));
        radioButtonPanel.setMaximumSize(getPreferredSize());
        radioButtonPanel.setPreferredSize(new java.awt.Dimension(295, 46));

        buttonGroup1.add(jRadioButton5x5);
        jRadioButton5x5.setText("5 x 5");
        jRadioButton5x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5x5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4x4);
        jRadioButton4x4.setSelected(true);
        jRadioButton4x4.setText("4 x 4");
        jRadioButton4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4x4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3x3);
        jRadioButton3x3.setText("3 x 3");
        jRadioButton3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3x3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout radioButtonPanelLayout = new javax.swing.GroupLayout(radioButtonPanel);
        radioButtonPanel.setLayout(radioButtonPanelLayout);
        radioButtonPanelLayout.setHorizontalGroup(
            radioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton3x3)
                .addGap(62, 62, 62)
                .addComponent(jRadioButton4x4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jRadioButton5x5)
                .addGap(15, 15, 15))
        );
        radioButtonPanelLayout.setVerticalGroup(
            radioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(radioButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton3x3)
                .addComponent(jRadioButton4x4)
                .addComponent(jRadioButton5x5))
        );

        boggleBoardScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        boggleBoardScrollPane.setHorizontalScrollBar(null);
        boggleBoardScrollPane.setMaximumSize(getPreferredSize());
        boggleBoardScrollPane.setMinimumSize(getPreferredSize());
        boggleBoardScrollPane.setPreferredSize(new java.awt.Dimension(302, 302));
        boggleBoardScrollPane.setWheelScrollingEnabled(false);

        boggleBoardPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(204, 204, 204))); // NOI18N
        boggleBoardPanel.setMaximumSize(getPreferredSize());
        boggleBoardPanel.setMinimumSize(getPreferredSize());
        boggleBoardPanel.setPreferredSize(new java.awt.Dimension(302, 302));
        boggleBoardPanel.setLayout(new java.awt.BorderLayout());
        boggleBoardScrollPane.setViewportView(boggleBoardPanel);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boggleBoardScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boggleBoardScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5x5ActionPerformed
        ROW_SIZE = 5;
        COL_SIZE = 5;
        createTable();
        BoggleDemo.playTimeCounter.start();
    }//GEN-LAST:event_jRadioButton5x5ActionPerformed

    private void jRadioButton4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4x4ActionPerformed
        ROW_SIZE = 4;
        COL_SIZE = 4;
        createTable();
        BoggleDemo.playTimeCounter.start();
    }//GEN-LAST:event_jRadioButton4x4ActionPerformed

    private void jRadioButton3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3x3ActionPerformed
        ROW_SIZE = 3;
        COL_SIZE = 3;
        createTable();
        BoggleDemo.playTimeCounter.start();
    }//GEN-LAST:event_jRadioButton3x3ActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        if (evt.getComponent() instanceof javax.swing.JPanel)
        {
            createTable();
            this.autoselectTableSize();
        }
    }//GEN-LAST:event_formComponentAdded

    public void autoselectTableSize() {
        
        switch (ROW_SIZE) {
            case 3:
                this.jRadioButton3x3.setSelected(true);
                break;
            
            case 4:
                this.jRadioButton4x4.setSelected(true);
                break;
                
            case 5:
                this.jRadioButton5x5.setSelected(true);
                break;
        }
    }
    
    
    // random boggle board based on alphabet frequencies
    private String[][] createBoggle()
    {
        // boggleStr used for object array in the GUI table
        String[][] boggleStr = new String[ROW_SIZE][COL_SIZE];
        boggle = BoggleDistribution.getRandomBoardFromAlphabetProbabilities(ROW_SIZE, COL_SIZE);
        
        for (int i = 0; i < ROW_SIZE; i++)
        {
            for (int j = 0; j < COL_SIZE; j++)
            {
                if (this.boggle[i][j] == 'Q')
                {
                    boggleStr[i][j] = "Qu";
                }
                else
                {
                    boggleStr[i][j] = String.valueOf(this.boggle[i][j]);
                }
            }
        }
        
        return boggleStr;
    }
    
    public void setCellBackground(int index, List<Integer> path) {
        int row = index/ROW_SIZE;
        int col = ((index % COL_SIZE) == 0 ? 0 : (index % COL_SIZE));
                    
        BoggleCellRenderer renderer = (BoggleCellRenderer)this.boggleTable.getCellRenderer(row, col);
        renderer.setCellColor(path);
    }
    
    public void repaintTable() {
        for (int i = 0; i < ROW_SIZE; i++) {
            for (int j = 0; j < COL_SIZE; j++) {
                BoggleCellRenderer renderer = (BoggleCellRenderer)this.boggleTable.getCellRenderer(i, j);
                renderer.resetCellColor(i, j);
            }
        }
        
        this.boggleTable.repaint();
    }
    
    public void createTable() {
        //clearTable();
        
        Object[][] boggleO = createBoggle();
        
        boggleTable = new javax.swing.JTable( );
        boggleTable.setRowHeight(this.cellWidth);
        boggleTable.setTableHeader(null); 
        boggleTable.setFocusable(false);
        
        boggleTable.setModel(new DefaultTableModel(boggleO, new Object[COL_SIZE]) {
            @Override
            public boolean isCellEditable(int i, int j)
            {
                return false;
            }
        });
        
        boggleTable.setAutoscrolls(false);
        boggleTable.setIntercellSpacing(new java.awt.Dimension(2, 2));
        boggleTable.setRowSelectionAllowed(false);
        boggleTable.setUpdateSelectionOnSort(false);
        boggleTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        boggleTable.setCellSelectionEnabled(false);
        boggleTable.setCellEditor(null);
        boggleTable.setMinimumSize(new java.awt.Dimension(344, 82));
        boggleTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        
        for (int i = 0; i < COL_SIZE; i++) {
            TableColumn column = this.boggleTable.getColumnModel().getColumn(i);
            BoggleCellRenderer renderer = new BoggleCellRenderer();
            column.setCellRenderer(renderer);
            column.setMaxWidth(this.cellWidth);
            column.setPreferredWidth(this.cellWidth);            
        }
        
       
        this.boggleBoardScrollPane.setViewportView(this.boggleTable);
    }
    
    
    private void clearTable()
    {
        if (boggleTable != null) {
            DefaultTableModel model = (DefaultTableModel) this.boggleTable.getModel();

            for (int i = (model.getRowCount() - 1); i >= 0; i--) {
                model.removeRow(i);
            }
        }
    }
    
    
    private JTable boggleTable;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boggleBoardPanel;
    private javax.swing.JScrollPane boggleBoardScrollPane;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton3x3;
    private javax.swing.JRadioButton jRadioButton4x4;
    private javax.swing.JRadioButton jRadioButton5x5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel radioButtonPanel;
    // End of variables declaration//GEN-END:variables
}
